{% set name = "pyFIt-SNE" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KlugerLab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d626260f36145057f226cf5739d7e6a591378f138f6e17b22fc3a12e12122d19

build:
  number: 5
  skip: true  # [win or py<=27]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - pip
    - fftw
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - fitsne

about:
  home: https://github.com/KlugerLab/pyFIt-SNE
  license: BSD-4-Clause
  license_file: LICENSE.txt
  summary: Python wrapper for FFT-accelerated Interpolation-based t-SNE (FIt-SNE) package.
  dev_url: https://github.com/KlugerLab/FIt-SNE

extra:
  recipe-maintainers:
    - yihming
    - bli25
